# Welcome {.unnumbered}

This is a template for creating (hand)books styled for VU Amsterdam. 

## Getting started

To get started you only need a GitHub account. You can [find the template directly on GitHub]({{< meta book.repo-url >}}).

To learn more about Quarto books visit <https://quarto.org/docs/books> [@knuth84]

Here is a checklist to ensure you set up the template correctly:

- [ ] Update `_quarto.yml`
    - [ ] Change title
    - [ ] `site-url` - `https://<username>.github.io/<repo>`
    - [ ] `repo-url` - `https://github.com/<username>/<repo>`
    - [ ] `issue-url` - `https://github.com/<username>/<repo>/issues/new/choose`

## Contributors


::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `warning`, `important`, `tip`, and `caution`.
:::

::: {.callout-warning}
## Warning with Title

This is an example of a callout with a title.
:::

::: {.callout-important}
## important with Title

This is an example of a callout with a title.
:::


::: {.callout-tip}
## Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
## Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::

